export CUDA_VISIBLE_DEVICES=0

model_name=LSWaveNet

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm1.csv \
  --model_id ETTm1_720_720 \
  --model $model_name \
  --data ETTm1 \
  --features M \
  --seq_len 720 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --d_model 512\
  --d_ff 512\
  --itr 1 \
  --lifting_levels 4\
  --lifting_kernel_size 7\
  --n_cluster 2\
  --learning_rate 0.0005\
  --batch_size 16\
  --train_epochs 5

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm1.csv \
  --model_id ETTm1_720_720 \
  --model $model_name \
  --data ETTm1 \
  --features M \
  --seq_len 720 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --d_model 512\
  --d_ff 512\
  --itr 1 \
  --lifting_levels 3\
  --lifting_kernel_size 7\
  --n_cluster 2\
  --learning_rate 0.0005\
  --batch_size 16

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm1.csv \
  --model_id ETTm1_720_720 \
  --model $model_name \
  --data ETTm1 \
  --features M \
  --seq_len 720 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --d_model 512\
  --d_ff 512\
  --itr 1 \
  --lifting_levels 2\
  --lifting_kernel_size 7\
  --n_cluster 2\
  --learning_rate 0.0005\
  --batch_size 16

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm1.csv \
  --model_id ETTm1_720_720 \
  --model $model_name \
  --data ETTm1 \
  --features M \
  --seq_len 720 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --d_model 512\
  --d_ff 512\
  --itr 1 \
  --lifting_levels 1\
  --lifting_kernel_size 7\
  --n_cluster 2\
  --learning_rate 0.0005\
  --batch_size 16